name: exc6

on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
    run-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pytest
      - run: pytest exercise_2
        continue-on-error: true

    update-badge:
      runs-on: ubuntu-latest
      needs: run-test
      steps:
      - uses: actions/checkout@v4
      - run: sed -i 's|https://img.shields.io/badge/tests-unknown-lightgrey|https://img.shields.io/badge/tests-passing-green|g' "README.md"
