name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"
  deploy-job:
    strategy:
      max-parallel: 1
      matrix:
        env: [dev, int, prod]
    runs-on: ubuntu-latest
    needs: job1
    environment: ${{matrix.env}}
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4
      - name: push_to_registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: exercise_3
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}-${{matrix.env}}/myapp:latest



  # Chain the next job to the previous one and make it deploy
  # to different environments with manual approvals